apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coursehub.fullname" . }}-db-init
  namespace: {{ .Values.namespace }}
data:
  01-schema.sql: |
{{ .Files.Get "database/schema.sql" | indent 4 }}
  02-seed.sql: |
{{ .Files.Get "database/seed.sql" | indent 4 }}
